In [1]:
import pandas as pd 
import numpy as np
import sklearn
from sklearn.utils import class_weight
from sklearn import model_selection, preprocessing, linear_model, naive_bayes, metrics, svm
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn import decomposition, ensemble
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import precision_score
from sklearn.model_selection import cross_validate
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import roc_auc_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import balanced_accuracy_score, recall_score, f1_score
from sklearn.metrics import make_scorer
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
import time

In [2]:
X_train = pd.read_csv('./data/X_train.csv')
X_test = pd.read_csv('./data/X_test.csv')
y_train = pd.read_csv('./data/y_train.csv')
y_test = pd.read_csv('./data/y_test.csv')
X_val = pd.read_csv('./data/X_val.csv')
y_val = pd.read_csv('./data/y_val.csv')

In [3]:
X_train = X_train.iloc[:,0]
X_test = X_test.iloc[:,0]
y_train = y_train.iloc[:,0]
y_test = y_test.iloc[:,0]
X_val = X_val.iloc[:,0]
y_val = y_val.iloc[:,0]
X_train

0        worse tea fresh green tea indeed green tea tim...
1        ive tasted best real things wonderful dreadful...
2        love taste good ginger snap cookie saw offered...
3        absolutely love coachs oatmeal hated oatmeal t...
4        normally dont go instant coffees delicious ins...
                               ...                        
96058    ive loved graham crackers since kid many brand...
96059    decided give try since kcup coffee prices goin...
96060    excellent coffee either brewed hot ice drink l...
96061    reading useful negative review times comment t...
96062    excited high protein pretzels opened tasted ta...
Name: text, Length: 96063, dtype: object

In [4]:
df = pd.DataFrame(data=[X_train, y_train], index=["text", "label"]).T
df = df.append(pd.DataFrame(data=[X_val, y_val], index=["text", "label"]).T)
df = df.append(pd.DataFrame(data=[X_test, y_test], index=["text", "label"]).T)

### One-Hot encoding (CountVectorizing)

In [5]:
# create a count vectorizer object 
count_vect = CountVectorizer(analyzer='word', token_pattern=r'\w{1,}')
count_vect.fit(df['text'])

# transform the training and validation data using count vectorizer object
xtrain_count =  count_vect.transform(X_train)
xvalid_count =  count_vect.transform(X_val)
xtest_count =  count_vect.transform(X_test)

### TF-IDF

In [6]:
# word level tf-idf
tfidf_vect = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=10000)
tfidf_vect.fit(df['text'])
xtrain_tfidf =  tfidf_vect.transform(X_train)
xvalid_tfidf =  tfidf_vect.transform(X_val)
xtest_tfidf =  tfidf_vect.transform(X_test)


# Model with Countvect

In [7]:
from sklearn import preprocessing, linear_model, naive_bayes, metrics, svm
model1 = naive_bayes.MultinomialNB()
model1.fit(xtrain_count,y_train)


MultinomialNB()

In [8]:
from sklearn.model_selection import cross_val_score
clf = naive_bayes.MultinomialNB()
scores = cross_val_score(clf, xvalid_count, y_val, cv=5)
scores

array([0.88992974, 0.88694566, 0.88663335, 0.88772642, 0.88538413])

In [9]:
 print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.89 accuracy with a standard deviation of 0.00


In [10]:
predictions = model1.predict(xtest_count)

In [11]:
print(confusion_matrix(y_test,predictions))

[[ 3938  1353]
 [ 1113 25618]]


In [12]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.78      0.74      0.76      5291
           1       0.95      0.96      0.95     26731

    accuracy                           0.92     32022
   macro avg       0.86      0.85      0.86     32022
weighted avg       0.92      0.92      0.92     32022



# Model with Tf-idf

In [13]:
model2= naive_bayes.MultinomialNB()
model2.fit(xtrain_tfidf,y_train)

MultinomialNB()

In [14]:
clf = naive_bayes.MultinomialNB()
scores = cross_val_score(clf, xvalid_tfidf, y_val, cv=5)
scores

array([0.86307572, 0.85805746, 0.85899438, 0.86367895, 0.85571518])

In [15]:
 print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.86 accuracy with a standard deviation of 0.00


In [17]:
predictions = model2.predict(xtest_tfidf)

In [18]:
print(confusion_matrix(y_test,predictions))

[[ 1702  3589]
 [  130 26601]]


In [19]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.93      0.32      0.48      5291
           1       0.88      1.00      0.93     26731

    accuracy                           0.88     32022
   macro avg       0.91      0.66      0.71     32022
weighted avg       0.89      0.88      0.86     32022

